---
title: "06 - Spike-In QC"
author: "jerod"
date: "June 29, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(cache = TRUE)
```

ERCC Dashboard
* Dashboard Plots

```{R}
# run the ERCC Dashboard on the appropriate count tables
# output from previous file:
metadatatable <- read.table(file="metadatatable.txt",sep=",",stringsAsFactors = FALSE,header = TRUE,colClasses = c(rep("character",10)))
Labid<-levels(as.factor(metadatatable$investigation))
mastercounttbl<-paste0(Labid,"_Transcript_Counts")
# this cloud app is defined by definedashboard.R and runs runDashboard.R.
  appid=p$app(name="runDashboardBeta")$id
    DBtsk <- p$task_add(name = paste("Beta_Dashboard_Analysis",sampleid,sep="_"), 
           description = paste("ERCC_Dashboard_Analysis of",sampleid,sep="_"), 
           app = appid,
           inputs = list(
              filenameRoot=sampleid,
              isNorm= FALSE,
              sample1Name: MixM,
              sample2Name: MixL,
              erccdilution: 1,
              spikeVol: 50,
              totalRNAmass: 2500,
              choseFDR= 0.05,
              source_file=p$file(name=mastercounttbl),
              erccmix="RatioPair"
           )
)
    DBtsk$run()
```
```{r output}
Figs<-p$file(id=DBtsk$outputs$DashboardFigures$path,limit=0)
DBobject<-p$file(id=DBtsk$outputs$data$path,limit=0)
# Display output from dashboard.
```